name: flet_spinkit
description: Flet FletSpinkit control
repository: https://github.com/MyGithubAccount/flet-spinkit/src/flutter/flet_spinkit
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-spinkit

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 
    git:
      url: https://github.com/flet-dev/flet.git
      ref: main
      path: packages/flet
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
